name: Terraform OCI Workflow

on:
  push:
    branches:
      - test-actions
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Terraform Cloud
        run: |
          echo "${{ secrets.HCP_TFC_TOKEN }}" > ~/.terraformrc
          echo 'credentials "app.terraform.io" { token = "'"${{ secrets.HCP_TFC_TOKEN }}"'" }' > ~/.terraformrc

      - name: Initialize Terraform
        working-directory: ./cloud-infrastructure
        run: terraform init

      - name: Verify Terraform Cloud Authentication
        working-directory: ./cloud-infrastructure
        run: terraform workspace list

      - name: Setup OCI Configuration
        run: |
          mkdir -p /home/runner/.oci
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > /home/runner/.oci/oci_api_key.pem
          chmod 600 /home/runner/.oci/oci_api_key.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Plan Terraform
        working-directory: ./cloud-infrastructure
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key_path: "/home/runner/.oci/oci_api_key.pem"
          TF_VAR_region: ${{ secrets.OCI_REGION }}
        run: terraform plan -out=plan.out

      - name: Apply Terraform
        if: github.event_name == 'push'
        working-directory: ./cloud-infrastructure
        env:
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
          TF_VAR_compartment_ocid: ${{ secrets.OCI_COMPARTMENT_OCID }}
          TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
          TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          TF_VAR_private_key_path: "/home/runner/.oci/oci_api_key.pem"
          TF_VAR_region: ${{ secrets.OCI_REGION }}
        run: terraform apply -auto-approve plan.out
